export const ACTIONS = {
  USER_DATA_LIST_LOADING: "USER_DATA_LIST_LOADING",
  POSTS_DATA_LIST_LOADING: "POSTS_DATA_LIST_LOADING",
  USER_DATA_LIST: "USER_DATA_LIST",
  POSTS_DATA_LIST: "POSTS_DATA_LIST",
  REJECT_ERROR: "REJECT_ERROR",
  CLEAR_USER_DATA_LIST: "CLEAR_USER_DATA_LIST",
  CLEAR_POSTS_DATA_LIST: "CLEAR_POSTS_DATA_LIST",
  ADD_SELECTED_DATA: "ADD_SELECTED_DATA",
  CLEAR_SELECTED_DATA: "CLEAR_SELECTED_DATA",
};
